### ISSUE TITLE
Seeds and Ban Addresses don't match

### ISSUE THREAD

**Issue by Unlifate** [alexanderdna/VanityAddrGen#1]
Those are some example outputs from result-dog.txt

> 28ED95CA880A059D8DF6994FCD39DAF2B3D89CC779F1245C162358C9F6568E86 ban_1dogsig36t9r1ms4qrqsxog69th83p8fjj8ejsb5e31bnsec1b6j761ee53j
> CED6B82FDACBDCADF08072A202E462CFD7DB9006CF2A400CF6FF298ED6E3705B ban_1dogbuxuy18tr3ei4cajtiqobetkpwgbef6ppbjyzs7gfe5rcwdkiesww86b
> 67E74EDA6D4E3A9312DEC8D457E097E9DD12254C0D5C4C5C4F43BD04FE9C242C ban_1dogyhczngkioa5bwdyq4zd3s64jqc7hrwub3xfhadew3qbbm4xdpma67gwf
> A2AC3C77C21BDBB0548E3A796F800EE76DFA950DF640809DE9BBB938C2807B64 ban_1dogbtui4otas8yjbitp8s3wh49qoqc5upi39rdpiwg1x345qctarsapqu83

They look legit. But if you test the seeds on [nano.tools](https://nanoo.tools/quick-banano-account) the resulting ban address will be wrong!

Well that's a major bug if you ask me. :)

I've installed this .NET Runtime 5.0.4: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.4-windows-x64-installer
My config is: 

> hardware=gpu
> match=prefix
> non_stop=1

If you need further PC information go ahead and feel free to ask :)

side note: on PC 2 it is working fine.

**Comment by alexanderdna** [comment]
I have run a test on my machine using both CPU and GPU. The results are as followed:

```
Seed: 28ED95CA880A059D8DF6994FCD39DAF2B3D89CC779F1245C162358C9F6568E86
Addr: ban_3hgwiyzxsm6nk1c8btyg1it7swindhe46c8bihy8e5yaek9ftue6zfimzu8f

Seed: CED6B82FDACBDCADF08072A202E462CFD7DB9006CF2A400CF6FF298ED6E3705B
Addr: ban_3k67hprqg7f9comn7wyqhwzsq8pa7ht63y4w8ukb6t7kusnshbfmpayru9kf

Seed: 67E74EDA6D4E3A9312DEC8D457E097E9DD12254C0D5C4C5C4F43BD04FE9C242C
Addr: ban_3p5qtmo98bppm4cieohot8cd5bthkkf1hyeakfp6dfgdbbqbaezgcnk3jufb

Seed: A2AC3C77C21BDBB0548E3A796F800EE76DFA950DF640809DE9BBB938C2807B64
Addr: ban_1gnr7baec7sp13iy47wcrzjntmzmmeu5jf4sizk6aqkpx1eftuq4cbmtsof8
```

It seems there were some issues with hardware, I guess. Please let me know the specs of your PCs.

My PC's specs, for reference:
```
CPU: Intel Core i7-8750H
GPU: NVIDIA GeForce GTX 1050 (Mobile)
```

**Comment by Unlifate** [comment]
my specs:
CPU: Intel Core i7-1065G7 CPU
GPU: Intel Iris Plus
RAM: 16 GB

**Comment by alexanderdna** [comment]
What are the results if you use `hardware=cpu` in config?

**Comment by Unlifate** [comment]
with `hardware=cpu`, the seed/addr generation works. With `gpu` it doesn't

**Comment by alexanderdna** [comment]
Currently I can't find out what happened to the GPU on your computer. However, to make sure users are aware of such problem, I have added a test at the beginning of the program. If user's GPU seems to produce an invalid address, the program will prompt an error message instead of proceeding the generation progress. Hope that helps.

**Comment by Unlifate** [comment]
sounds good. I will download again, when release is out :)

**Comment by alexanderdna** [comment]
Marked as closed since it's been too long.
