### ISSUE TITLE
Any chance to have a non-windows port?

### ISSUE THREAD

**Issue by lsteffenel** [alexanderdna/VanityAddrGen#2]
Hi! I would like to thank you for your work, and ask if there is a chance to have a more "platform-generic" code. I know that Mono can be used to compile C# on linux, but it would be nice to have the application written on something more universal such as C/C++ or Python.

Thank you!

**Comment by alexanderdna** [comment]
Hi! This project is developed on .net 5 which is cross-platform. You can compile it using the .net sdk for Windows or Linux.
