### ISSUE TITLE
Cloo.BuildProgramFailureComputeException: "OpenCL error code detected: BuildProgramFailure."

### ISSUE THREAD

**Issue by Snowli11** [alexanderdna/VanityAddrGen#3]
The program crashes every time before it starts generating keys.
![image](https://user-images.githubusercontent.com/62450413/120888696-0b7a6a80-c5fa-11eb-8ded-a73266edb696.png)

In visual studio i get Cloo.BuildProgramFailureComputeException: "OpenCL error code detected: BuildProgramFailure." at line 71:
 
`ComputeKernel kernel = program.CreateKernel("generate_pubkey");`

Config:
[config.txt](https://github.com/alexanderdna/VanityAddrGen/files/6602393/config.txt)

**Comment by brimmlessyankee** [comment]
I have the exact same error. I reinstalled windows but the error still occurs. Really sucks. CPU mode works but it slow asf

**Comment by alexanderdna** [comment]
This looks like a compatibility issue with OpenCL hardware. I will try to inspect what went wrong.

**Comment by alexanderdna** [comment]
Fixed in v1.1.4
