### ISSUE TITLE
Unhandled exception. Cloo.BuildProgramFailureComputeException: OpenCL error code detected: BuildProgramFailure.

### ISSUE THREAD

**Issue by nishanchx** [alexanderdna/VanityAddrGen#4]
Can't run it, just gives unhandled exception. Running on GTX 1060.
![vanity](https://user-images.githubusercontent.com/86910576/124379864-35967980-dcd9-11eb-8444-32337352b377.png)

**Comment by MiranDaniel** [comment]
I get the same error on a RTX 3060 and a 3090

**Comment by dev-ptera** [comment]
Same here on a GTX1080

**Comment by alexanderdna** [comment]
It turned out to be a compatibility issue with newer versions of NVIDIA drivers. I fixed that in v1.1.4.
